//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TextImageGenerator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TextImageGenerator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 阿
        ///啊
        ///锕
        ///呵
        ///吖
        ///腌
        ///錒
        ///嗄
        ///呵
        ///啊
        ///呵
        ///啊
        ///啊
        ///呵
        ///阿
        ///啊
        ///埃
        ///哎
        ///唉
        ///哀
        ///挨
        ///锿
        ///嗳
        ///捱
        ///欸
        ///溾
        ///鎄
        ///娭
        ///噯
        ///癌
        ///挨
        ///捱
        ///皑
        ///磑
        ///硙
        ///皚
        ///溰
        ///敳
        ///敱
        ///隑
        ///嵦
        ///娾
        ///騃
        ///嘊
        ///啀
        ///凒
        ///矮
        ///霭
        ///蔼
        ///哎
        ///嗳
        ///欸
        ///毐
        ///藹
        ///絠
        ///譪
        ///躷
        ///濭
        ///昹
        ///靄
        ///娾
        ///噯
        ///爱
        ///艾
        ///碍
        ///隘
        ///嗳
        ///暧
        ///瑷
        ///嫒
        ///哎
        ///唉
        ///嗌
        ///砹
        ///乂
        ///薆
        ///礙
        ///硋
        ///譺
        ///瞹
        ///皧
        ///賹
        ///璦
        ///焥
        ///醷
        ///曖
        ///鑀
        ///閡
        ///懝
        ///懓
        ///愛
        ///阨
        ///阸
        ///靉
        ///嬡
        ///餲
        ///馤
        ///壒
        ///塧
        ///堨
        ///噯
        ///呝
        ///叆
        ///鴱
        ///僾
        ///伌
        ///安
        ///庵
        ///厂
        ///氨
        ///谙
        ///鞍
        ///桉
        ///广
        ///鹌
        ///盦
        ///蓭
        ///葊
        ///萻
        ///菴
        ///腤
        ///裺
        ///誝
        ///諳
        ///盫
        ///痷
        ///闇
        ///廣
        ///鞌
        ///韽
        ///峖
        ///媕
        ///馣
        ///啽
        ///鮟
        ///鵪
        ///鶕
        ///侒
        ///俺
        ///铵
        ///埯
        ///揞
        ///罯
        ///碪
        ///銨
        ///晻
        ///隌
        ///垵
        ///唵
        ///侒
        ///按
        ///案
        ///岸
        ///暗
        ///胺
        ///黯
        ///犴
        ///荌
        ///豻
        ///貋
        ///洝
        ///晻
        ///錌
        ///闇
        ///頇
        ///頞
        ///屽
        ///婩
        ///堓
        ///垾
        ///鮟        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GBK {
            get {
                return ResourceManager.GetString("GBK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 的
        ///一
        ///是
        ///在
        ///不
        ///了
        ///有
        ///和
        ///人
        ///这
        ///中
        ///大
        ///为
        ///上
        ///个
        ///国
        ///我
        ///以
        ///要
        ///他
        ///时
        ///来
        ///用
        ///们
        ///生
        ///到
        ///作
        ///地
        ///于
        ///出
        ///就
        ///分
        ///对
        ///成
        ///会
        ///可
        ///主
        ///发
        ///年
        ///动
        ///同
        ///工
        ///也
        ///能
        ///下
        ///过
        ///子
        ///说
        ///产
        ///在
        ///不
        ///了
        ///有
        ///和
        ///人
        ///这
        ///中
        ///大
        ///为
        ///上
        ///而
        ///方
        ///后
        ///多
        ///在
        ///不
        ///了
        ///有
        ///和
        ///人
        ///这
        ///中
        ///大
        ///为
        ///上
        ///法
        ///所
        ///民
        ///得
        ///经
        ///十
        ///三
        ///之
        ///进
        ///着
        ///等
        ///部
        ///度
        ///家
        ///电
        ///力
        ///里
        ///如
        ///水
        ///化
        ///高
        ///自
        ///二
        ///理
        ///起
        ///小
        ///物
        ///现
        ///实
        ///加
        ///量
        ///都
        ///两
        ///体
        ///制
        ///机
        ///当
        ///使
        ///点
        ///从
        ///业
        ///本
        ///去
        ///把
        ///性
        ///好
        ///应
        ///开
        ///它
        ///合
        ///还
        ///因
        ///由
        ///其
        ///些
        ///然
        ///前
        ///外
        ///天
        ///政
        ///四
        ///日
        ///那
        ///社
        ///义
        ///事
        ///平
        ///形
        ///相
        ///全
        ///表
        ///间
        ///样
        ///与
        ///关
        ///各
        ///重
        ///新
        ///线
        ///内
        ///数
        ///正
        ///心
        ///反
        ///你
        ///明
        ///看
        ///原
        ///又
        ///么
        ///利
        ///比
        ///或
        ///但
        ///质
        ///气        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SCTOP3K {
            get {
                return ResourceManager.GetString("SCTOP3K", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 的
        ///一
        ///是
        ///在
        ///不
        ///了
        ///有
        ///和
        ///人
        ///這
        ///中
        ///大
        ///為
        ///上
        ///個
        ///國
        ///我
        ///以
        ///要
        ///他
        ///時
        ///來
        ///用
        ///們
        ///生
        ///到
        ///作
        ///地
        ///於
        ///出
        ///就
        ///分
        ///對
        ///成
        ///會
        ///可
        ///主
        ///發
        ///年
        ///動
        ///同
        ///工
        ///也
        ///能
        ///下
        ///過
        ///子
        ///說
        ///產
        ///種
        ///面
        ///而
        ///方
        ///後
        ///多
        ///定
        ///行
        ///學
        ///法
        ///所
        ///民
        ///得
        ///經
        ///十
        ///三
        ///之
        ///進
        ///著
        ///等
        ///部
        ///度
        ///家
        ///電
        ///力
        ///裏
        ///如
        ///水
        ///化
        ///高
        ///自
        ///二
        ///理
        ///起
        ///小
        ///物
        ///現
        ///實
        ///加
        ///量
        ///都
        ///兩
        ///體
        ///制
        ///機
        ///當
        ///使
        ///點
        ///從
        ///業
        ///本
        ///去
        ///把
        ///性
        ///好
        ///應
        ///開
        ///它
        ///合
        ///還
        ///因
        ///由
        ///其
        ///些
        ///然
        ///前
        ///外
        ///天
        ///政
        ///四
        ///日
        ///那
        ///社
        ///義
        ///事
        ///平
        ///形
        ///相
        ///全
        ///表
        ///間
        ///樣
        ///與
        ///關
        ///各
        ///重
        ///新
        ///線
        ///內
        ///數
        ///正
        ///心
        ///反
        ///你
        ///明
        ///看
        ///原
        ///又
        ///麽
        ///利
        ///比
        ///或
        ///但
        ///質
        ///氣
        ///第
        ///向
        ///道
        ///命
        ///此
        ///變
        ///條
        ///只
        ///沒
        ///結
        ///解
        ///問
        ///意
        ///建
        ///月
        ///公
        ///無        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TCTOP3K {
            get {
                return ResourceManager.GetString("TCTOP3K", resourceCulture);
            }
        }
    }
}
